spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/taskmanager}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:dev-local-only-UseStrongPassword!2026}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'Asia/Kolkata'

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG